version: '3.8'

services:
  web:
    container_name: web
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  database:
    ports:
      - "5432:5432"
    container_name: postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${DB_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data: